### ISSUE TITLE
Setup markdown - Azure CLI

### ISSUE THREAD

**Issue by bspann** [Microsoft/MCW-Containers-and-DevOps#10]
In the setup.md file, Task 11 has outdated instructions to download the Azure-CLI.  Following the link provided works to download and install the Azure-CLI for Linux.

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Comment by jamesrcounts** [comment]
Hi there, I double checked the instructions in the June-2018-update branch and they appear to be updated and match the instructions from the link you referenced.

**Comment by DawnmarieDesJardins** [comment]
Closing, correct in June 2018 branch
