### ISSUE TITLE
September 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Containers-and-DevOps#104]
This MCW is scheduled for content update.
Solliance - please review current content and all open issues and recommended updates for SME review.

**Comment by DawnmarieDesJardins** [comment]
Solliance team - please see Issue #105 and incorporate into current update.

**Comment by jamesrcounts** [comment]
Here is the current plan as I understand it:

* Update title to "Cloud Native Applications"
* Revisit efficiencies in lab setup
  * Look to reduce number of setup steps
  * Remove unecessary VMs 
  * Leverage Azure Cloud Shell
  * Leverage Azure Cloud Shell Code editor
* Discuss container scanning in WDS
  * Feature currently in private preview making lab support difficult--can revisit when it hits public preview
* Leverage YAML for CI pipeline setup
* Review kubernetes flow/setup for current best practices
* Remove bower, replace with npm
* Incorporate feedback from issues:
  * #105 - Incorporate language changes 
   * #103 - Test ARM template is deploying cosmos to requested region, verify node version used in lab
  * #102 - container scanning
  * #97 - Yaml based CI
  * #92 - Update mongoose npm package and test for cosmosdb connection fail
  * #90 - Replace bower with npm (also resolves #37)
  * #39 - verify az cli is working (already available in cloud shell)
  * #38 - update screenshots (if there are significant differences in layouts or defaults)

**Comment by woutervanranst** [comment]
The command
`kubectl` get -o=yaml --export=true deployment api > api.deployment.yml
returns  "Flag --export has been deprecated, This flag is deprecated and will be removed in future."

**Comment by woutervanranst** [comment]
The step 

> Select "+ Create a Resource" and search for "Application Insights" and select "Application Insights".

Both app insights are already created by the ARM app insights already created

**Comment by jamesrcounts** [comment]
> The step
> 
> > Select "+ Create a Resource" and search for "Application Insights" and select "Application Insights".
> 
> Both app insights are already created by the ARM template

Thanks, just double checked and this is corrected in #109

**Comment by DawnmarieDesJardins** [comment]
Closing with merge of the update PR.
