### ISSUE TITLE
Minor changes requested to Whiteboard design session/WDS trainer presentation - Containers and DevOps.pptx

### ISSUE THREAD

**Issue by stefsch** [microsoft/MCW-Containers-and-DevOps#105]
On slide 20:

First bullet point - please change:
"App Service for Containers – simple, PaaS without robust orchestration platform management tooling"
--to--
"App Service for Containers – simple PaaS without full-featured container orchestration"

Speaker notes - please change:
"The easiest way to move to containers on Azure is to deploy containers to App Service for Containers, however, this option does not provide the typical management tools for container orchestration – that can provide load balancing, dynamic discovery, self-healing, and a holistic approach to container monitoring."

--to--

"The easiest way to move to containers on Azure is to deploy containers to the Linux variant of App Service.  However this option does not provide a full-featured container orchestration platform with highly customizable load balancing, dynamic service discovery, and a holistic approach to container monitoring."

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.  Addressed in the recent update.
