### ISSUE TITLE
Before the HoL / azuredeploy.parameters.json Suffix

### ISSUE THREAD

**Issue by woutervanranst** [microsoft/MCW-Containers-and-DevOps#106]
When I use "Suffix: Enter something like "SUF" with max of 3 chars." as described, I get the error

Deployment failed. Correlation ID: e75402b0-2491-4ebc-832a-3eca7fc112d2. {
  "code": "BadRequest",
  "message": "The character 'W' at index 11 is not allowed in the DatabaseAccount name\r\nActivityId: 90e061ff-56eb-4b92-bd7c-a367df7dcd42, Microsoft.Azure.Documents.Common/2.5.1"
}

Solution is to have a lowercase suffix - please document this

**Comment by jamesrcounts** [comment]
@DawnmarieDesJardins I believe this will be updated in the September update.  ARM template should now lowercase as needed automatically.

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.  Addressed in the recent update.
