### ISSUE TITLE
Before the HoL / Bower Installation

### ISSUE THREAD

**Issue by woutervanranst** [microsoft/MCW-Containers-and-DevOps#107]
* Bower sends a warning that it is deprecated and further gave a permission issue and failed to install

Commands to resolve:

sudo chown -R $USER /usr/lib/node_modules
sudo su
npm install -g bower

**Comment by jamesrcounts** [comment]
Bower will no longer be part of the lab after the September update (#104)

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.  Addressed in the recent update.
