### ISSUE TITLE
HOL step-by-step

### ISSUE THREAD

**Issue by bspann** [Microsoft/MCW-Containers-and-DevOps#11]
Task 4 step 6 has an extra "-" before the t argument.
Task 6 step 12 has a free-floating "c" before content-web.  This will cause problems if not removed.
Task 7 step 4 has an extra "-" in front of both u & p in the sample bash command.

**Comment by jamesrcounts** [comment]
Hello, these issues appear to be resolved in the June-2018-update branch

**Comment by DawnmarieDesJardins** [comment]
Closing, correct in June 2018 update branch
