### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by dzaremba90** [Microsoft/MCW-Containers-and-DevOps#12]
The readme doc is missing the bulleted portion for the HOL and WDS abstracts. Please update to the following: 

HOL
This hands-on lab is designed to guide you through the process of building and deploying Docker images to the Kubernetes platform hosted on Azure Container Services (AKS) in addition to learning how to work with dynamic service discovery, service scale-out and HA. The goal of the lab is to provide a foundation for the following:
•	Creating the following Azure resources:
o	Azure Container Registry
o	Azure Container Services (AKS)
•	Setting up an environment to do the following:
o	Build Docker images
o	Connect to Azure Container Registry
o	Connect to an Azure Container Services (AKS) cluster
•	Perform the following actions:
o	Building Docker images locally and pushing them to Azure Container Registry
o	Deploying containers to a Kubernetes cluster
o	Load balancing containers with and without Azure Load Balancer
o	Working with service discovery
o	Performing rolling upgrades for services with zero downtime
o	Scaling services

WDS
This whiteboard design session is designed to help attendees understand the choices related to building and deploying containerized applications in Azure, critical decisions around this and other aspects of the solution including ways to lift-and-shift parts of the application to reduce applications changes. In addition,
•	Create and run a Docker Application
•	Deploy to the Azure Container Service (AKS)
•	Implement load balancing and service discovery
•	Scale the application and test availability

**Comment by michelebusta** [comment]
Please confirm if this is still an issue, I believe the discussion we had indicates we are no longer doing "bullets". Let me know :)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as we are moving away from bulleted abstracts.
