### ISSUE TITLE
Before the lab doc

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Containers-and-DevOps#17]
Line 596 forward
There's a grey box around the steps and the images aren't showing.  Not sure what code is causing that.

**Comment by michelebusta** [comment]
all fixed

**Comment by DawnmarieDesJardins** [comment]
Thanks Michele - that looks much better.  
Couple of questions though - 
Line 568 says: curl -L -o FabMedical.tgz <TODO ADD BITLY LINK>  Is this a TODO that got missed, or is it really supposed to be TODO....?
Line 688 says: git clone <REPOSITORY_URL> - are we missing a URL?

**Comment by jamesrcounts** [comment]
Line 688 is correct as is, it's a variable where the student should paste the URL that copied by following the instructions on line 683.

Line 568 is a genuine TODO.  We need a bitly link (or similar) for the starter files which redirects to the starter files hosted in this repository: https://github.com/Microsoft/MCW-Containers-and-DevOps/raw/master/HOL/FabMedical.tar.gz

**Comment by michelebusta** [comment]
bit.ly updated
