### ISSUE TITLE
Exercise 2, Task 4 - step 2 Missing content-init image from ACR

### ISSUE THREAD

**Issue by bspann** [Microsoft/MCW-Containers-and-DevOps#24]
The init.job.yml is referencing an image from ACR that was not initially pushed.  To fix this, Exercise 1, Task 7 - step 5 needs the following line added:

docker tag content-init [LOGINSERVER]/content-init

Task 7 - step 7 needs the following line added:

docker push [LOGINSERVER]/content-init

step 10 needs the following line added (optional):
docker tag [LOGINSERVER]/content-init:latest [LOGINSERVER]/content-init:v1

**Comment by jamesrcounts** [comment]
The content init image should have been created by VSTS after setting up the content-init build in Ex 1, Task 7, Step 27.

**Comment by michelebusta** [comment]
Is this resolved then?

**Comment by roberto-mardeni** [comment]
I just ran this workshop yesterday and concur with @jamesrcounts , this issue should be closed.

**Comment by waltermyersiii** [comment]
I will go ahead and close.

**Comment by waltermyersiii** [comment]
Closed per @jamesrcounts and @roberto-mardeni.
