### ISSUE TITLE
Ready for review and QC

### ISSUE THREAD

**Issue by kylebunting** [Microsoft/MCW-Containers-and-DevOps#36]
The august-2018-testfix branch is ready for review and QC.

**Comment by DawnmarieDesJardins** [comment]
Added Jay as it looks like he corrected the open issue I created yesterday.  This one is reviewed on my side, excellent job as usual, I only found a couple of things that need a peek.  I see several field issues that opened about the time this test/fix came through, please close any that have been addressed in the test/fix.  Thanks! Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Hi Jay, I tried to merge this test/fix with the master as it looks like the issues have been addressed but I'm getting a merge conflict.  Please take a peek, resolve the conflict and merge this one - then we're all complete for August.  It's something to do with adding AZURE-REGION in a link.  Thanks much!

**Comment by waltermyersiii** [comment]
Jay,

Since you forked, there were some updates to put placeholders for Azure region.  Check on the master where you see [AZURE-REGION] and put those placeholders in your forked repo.

Walter

**Comment by jstulo** [comment]
I will merge this today.

Jay
