### ISSUE TITLE
Install Bower NPM Warn message

### ISSUE THREAD

**Issue by Roydemilde** [microsoft/MCW-Containers-and-DevOps#37]
HOL -> Before the HOL -> Task 7 -> Step 10
Add a short text that you receive a NPM warning message when you try to install Bower. User can ignore the NPM warning.
![npm warn message](https://user-images.githubusercontent.com/11046097/44795707-a624ff80-abab-11e8-8d45-65756564fbac.png)

**Comment by jschluchter** [comment]
You may, or may not, see this error, given the fluid nature of dependent npm packages version updates. We can adjust the language to note this.

**Comment by mousling** [comment]
I am blocked on the task 4.7 . Any Idea please how i can resolve this? Thanks
![Fehler](https://user-images.githubusercontent.com/48826514/55145220-a3d75380-5142-11e9-846d-567b4af20b2f.png)

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.  Addressed in the recent update.
