### ISSUE TITLE
Azure blade pictures are outdated

### ISSUE THREAD

**Issue by Roydemilde** [microsoft/MCW-Containers-and-DevOps#38]
HOL -> Before the HOL -> Task 10 -> Step 2
Pictures used are outdated. Please update to the new Azure blade look

**Comment by kevinhillinger** [comment]
Task 10 is being mentioned by @Roydemilde but going through a lot of the screenshots, many, if not most are out dated. This includes default values the portal sets for the user, which is important in the case of things like security options.

One way of solving this would be to continue to update the screenshots with latest. The challenge with this is screenshot continuity. A second way of solving this is to update tasks, where possible, to use Azure Cloud Shell and CLI.

My suggestion would be to do the latter.

**Comment by waltermyersiii** [comment]
Thanks, Kevin. Looking forward to meeting next week to discuss an out of band PR to fix at least some of the issues. :-)

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.  Addressed in the recent update.
