### ISSUE TITLE
Can't we use Azure Cloud Shell (CLI) instead of Win 10 VM setup ?

### ISSUE THREAD

**Issue by sowsan** [Microsoft/MCW-Containers-and-DevOps#42]
Just to check on the step to setup win 10 VM with WASL to configure build VM (ubuntu), can't we use Azure Cloud Shell with CLI for that instead of setting up another VM ?

**Comment by jamesrcounts** [comment]
I believe the reason we rejected this option is that later on in the lab you will need a "local" shell in order to create the tunnel to the kubernetes dashboard.

Even though the VM isn't local it meets the requirement because it has access to a full Windows desktop environment.

**Comment by sowsan** [comment]
Make sense. Thank you!

**Comment by benc-uk** [comment]
@jamesrcounts - could you look at this again?

The `az aks browse` part now works in the Cloud Shell, it opens a gateway and the Kubernetes dashboard in a new browser tab

I moved my Kubernetes lab over to 100% Cloud Shell and it's 100% better than asking people to build a VM, which is a very old fashioned approach to labs IMO
