### ISSUE TITLE
Authentication Failure to Azure DevOps VSTS Repo

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Containers-and-DevOps#49]
In Before hands on lab, **Task 13 -> Step 7** -> while running command: **git push -u origin  -all** authentication is failing even when we provide the correct password.

![image](https://user-images.githubusercontent.com/38715522/47711673-c6307800-dc5b-11e8-8b98-cdbc6d2a97d1.png)

**Comment by DawnmarieDesJardins** [comment]
Assigning to Jay @jstulo.  Jay, you're working on this one, correct?

**Comment by jstulo** [comment]
This one is on my schedule for text-fix in November, but I will look into this today.

**Comment by jstulo** [comment]
There are some updates that will be made to this lab soon. The change from VSTS to Azure DevOps has introduced a couple of issues. To resolve this issue be sure that when you add the remote you remove the username@ from the url. You will be prompted for username and password from your git alternate credentials when you push in the next step, but this will solve the issue for now.

![image](https://user-images.githubusercontent.com/9166228/47810898-621cbb00-dd12-11e8-82cb-dae0ea460716.png)
