### ISSUE TITLE
Task 13 Git push fails

### ISSUE THREAD

**Issue by Jiihaa** [Microsoft/MCW-Containers-and-DevOps#50]
Is there a missing configuration step or have things changed since I create the repo, and set origin and when I try to push, it fails with:
XXXadmin@fabmedical-XX:~/FabMedical/content-web$ git push -u origin --all
Password for 'https://fabmedical-XX@dev.azure.com':
fatal: Authentication failed for 'https://fabmedical-XX@dev.azure.com/fabmedical-XX/fabmedical/_git/content-web/'

I tried changing the password until it locked me out of changing it anymore in 24 h period, so pretty sure there's no type there.

**Comment by jstulo** [comment]
Please see the resolution mentioned here: https://github.com/Microsoft/MCW-Containers-and-DevOps/issues/49#issuecomment-434801602

**Comment by Jiihaa** [comment]
That seems to do the trick, thank you!
