### ISSUE TITLE
Add Terraform Deployment Of AKS

### ISSUE THREAD

**Issue by dstrebel** [microsoft/MCW-Containers-and-DevOps#6]
Use Terraform to deploy AKS, as this is a common and recommend scenario.

**Comment by michelebusta** [comment]
agree re: terraform being a common tool, was not in scope for the rewrite but perhaps in future they'll add that to this lab

**Comment by waltermyersiii** [comment]
Marking as future enhancement.

**Comment by jschluchter** [comment]
Assigning @dstrebel

**Comment by kevinhillinger** [comment]
@dstrebel any progress on this? I'm evaluating whether to assist with providing enhancements to the ["Before the HOL"](Hands-on lab/Before the HOL - Containers and DevOps.md) content, including templating out AKS.

to provide a cohesive / consistent lab experience, we may want to consider templates for the entire setup process, and not just a one off with AKS. Thoughts?

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.  Addressed in the recent update.
