### ISSUE TITLE
March 2019 - Scheduled content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Containers-and-DevOps#66]
@ZoinerTejada @joelhulen @kylebunting
Solliance team -
This workshop is scheduled for an update in March. On top of updating the current information, we will be adding an Infra WDS and lab version.  Please update this issue with suggested content changes. Once done, we'll assign to our SME team for review and additional feedback.

**Comment by jamesrcounts** [comment]
@DawnmarieDesJardins,

After discussing on our side we would suggest the following content changes:

- Review lab for latest screens, terminology (Azure DevOps has iterated rapidly this year)
- Add exercise for authoring helm charts to support Continuous Deployment (CD) exercises.
- Add CD exercise (create an AKS deployment pipeline in Azure DevOps)
- Add some logging to the solution for Application Insights, add exercise to review these logs.
- Add Azure Monitor for Containers, add exercise to review logs/dashboards available in Azure Portal.
- Create infrastructure lab separate from dev lab; remove dev features keeping all other features

**Comment by waltermyersiii** [comment]
Looks good. I have also asked our Azure Monitor team to weigh in.

**Comment by Roydemilde** [comment]
Infrastructure is focussing more on Security within AKS?

**Comment by jamesrcounts** [comment]
My understanding of the infrastructure lab is that it is a different version of the same content.  The topics and exercises will be the same, except the infrastructure lab will only focus on the operations side of things, and exercises that focus on code changes, etc will be simplified or left out.

**Comment by DawnmarieDesJardins** [comment]
@waltermyersiii @bendq @ChongRX78
Hello gentlemen,
Please verify @jamesrcounts comment above to make sure we are clear on the direction of this update.
Thanks, Dawnmarie

**Comment by waltermyersiii** [comment]
Yes, that is correct, James. There may be some specifics on the infra side that Ben and Chong want to contribute.

**Comment by DawnmarieDesJardins** [comment]
Please see open issue #69 when working this update.

**Comment by joelhulen** [comment]
@waltermyersiii @DawnmarieDesJardins can you sign off on the suggested updates?

**Comment by waltermyersiii** [comment]
Yes, you have my sign off. :-)

**Comment by waltermyersiii** [comment]
Please include this from Carlos Reyes: Command "az acs" is (will be) deprecated, so please update Task 12 from "sudo az acs kubernetes install-cli --install-location /usr/local/bin/kubectl" to "sudo az aks install-cli ..."

**Comment by wely** [comment]
Hi guys,

When do you plan to update to the march one?

**Comment by waltermyersiii** [comment]
Hi Wely,

Soon. Working on it now.

**Comment by waltermyersiii** [comment]
To be more precise, it will be updated in time for April Boot Camp, which is the week of April 8.

**Comment by PeterKessler** [comment]
Is the timetable still valid? Can I expect an update today/tomorrow?

**Comment by DawnmarieDesJardins** [comment]
@PeterKessler @waltermyersiii 
Hi Peter,
The updated whiteboard design session documents were updated 4/5.  Our authors are working on feedback updates to the lab.  Updated lab information will be complete by 5/3.
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing issue, addressed in March 2019 update
