### ISSUE TITLE
Issue when running bower install

### ISSUE THREAD

**Issue by logcorner** [Microsoft/MCW-Containers-and-DevOps#67]
Hi,
I got an issue installing bower 
Task 1: Test the application 

13...
cd ../content-web
npm install
bower install
![bower](https://user-images.githubusercontent.com/5066547/53164537-b2c16800-35d0-11e9-8383-a863da67069f.png)

regards

**Comment by jamesrcounts** [comment]
Can you run `ls -la` in the folder where the file exists and show us the results?

**Comment by jamesrcounts** [comment]
Super, those are exactly the steps I would have recommended.  Just wanted to verify you were in that situation first.
