### ISSUE TITLE
Lab Suggestions

### ISSUE THREAD

**Issue by undiscovereddev** [Microsoft/MCW-Containers-and-DevOps#72]
Hey all,

I ran the lab last week before running the class in London and it took over 8 hours.  I have seen some feedback from the class in Ireland and they made the same comment.  I have found that there are a few bugs, including administrator permissions not set for the ssh administrator initially on the ubuntu vm.  I ran the following command ($sudo chown -R <username> .config).
I also ran into a problem with Azure DevOps, where I could not create a Build Pipeline, because the classic interface does not allow the use of ubuntu 18.04, instead 16.04, so a yaml configuration file would need to be created.
I found that all the commands needed to be precise and were way too long for the 3-4 hours allotted.  I had to run the lab 4x on my own before I could get to the last part of Exercise 1 before I realized that I could not get the DevOps pipeline to work.   I hope that these comments help with the future releases.

Sincerely,
Becky Isserman

**Comment by waltermyersiii** [comment]
Hi Becky,

Thanks for the feedback. Typically this lab does take about 4 hours, but it has aged a bit and we are currently going through an update cycle. Will factor this feedback into the update. BTW, the lab calls for Ubuntu 16.04, so unfortunately you chose the wrong machine that caused you trouble.

Walter

**Comment by DawnmarieDesJardins** [comment]
Closing issue, addressed as in March 2019 update
