### ISSUE TITLE
Excercise 4, task 7: Type the following command to create a Docker image for the web application

### ISSUE THREAD

**Issue by mousling** [Microsoft/MCW-Containers-and-DevOps#73]
I am blockt hier with an error message. Can anyone please help! Thank you
![Fehler](https://user-images.githubusercontent.com/48826514/55145872-db92cb00-5143-11e9-8605-a546ecda14a2.png)

**Comment by DawnmarieDesJardins** [comment]
Hello, we just completed an update to this lab.  Please review and reopen if that does not solve your issue.  Thanks!
