### ISSUE TITLE
Task 12 of Before Hands of Lab

### ISSUE THREAD

**Issue by karlitoz007** [Microsoft/MCW-Containers-and-DevOps#74]
Command "az acs" is (will be) deprecated, so please update Task 12 from "sudo **az acs kubernetes** install-cli --install-location /usr/local/bin/kubectl" to "sudo **az aks** install-cli ..."... Thanks!

**Comment by karlitoz007** [comment]
Note: This PR includes this fix https://github.com/Microsoft/MCW-Containers-and-DevOps/pull/71

**Comment by waltermyersiii** [comment]
Carlos, we are currently going through an update so wouldn't be able to process the PR until after (and you would have to refresh). I will pass this on to the vendor to include in the update.

**Comment by jamesrcounts** [comment]
Appears to duplicate #47

**Comment by jamesrcounts** [comment]
Fixed in #83
