### ISSUE TITLE
Azure DevOps branding in azure-devops-aks.png

### ISSUE THREAD

**Issue by dmckinstry** [Microsoft/MCW-Containers-and-DevOps#84]
Can we update "media/azure-devops-aks.png" to use individual service names and logos (per corporate guidance):

- "Azure Repos" (and the Repos icon) instead of "Azure DevOps Git", 
- "Azure Pipelines (build and package)" instead of "Azure DevOps CI",
- "Azure Pipelines (Release)" instead of "Azure DevOps CD",
- "Azure Boards (Backlog)" instead of "Azure DevOps Backlog"

Since this is Node, shouldn't we also be using Visual Studio Code (name and icon) instead of Visual Studio?

**Comment by jamesrcounts** [comment]
This feedback appears to line up with the image currently on master, it has been replaced in #83.
