### ISSUE TITLE
Changes requested for WDS student guide - Containers and DevOps.md

### ISSUE THREAD

**Issue by stefsch** [Microsoft/MCW-Containers-and-DevOps#86]
Please change the sentence:

“What is the simplest way to move to containers on Azure, based on our PaaS experience, while at the same time considering our scale and growth requirements?”  

--to--

 “What is the simplest way to move to containers on Azure, while at the same time considering our scale and growth requirements?”

**Comment by jamesrcounts** [comment]
Thanks for the feedback!
