### ISSUE TITLE
Changes requested to WDS trainer guide - Containers and DevOps.md

### ISSUE THREAD

**Issue by stefsch** [Microsoft/MCW-Containers-and-DevOps#87]
Please change:
“What is the simplest way to move to containers on Azure, based on our PaaS experience, while at the same time considering our scale and growth requirements?”  
--to--
"What is the simplest way to move to containers on Azure, while at the same time considering our scale and growth requirements?”

Please change:
“Azure App Service specifically targets container deployments, which makes it easy to deploy container instances to a fully managed App Service Plan. This option is ideal for smaller solutions with a limited number of containers or that do not require an orchestration platform.”
--to--
“Azure App Service specifically targets container deployments, which makes it easy to deploy container instances to a fully managed App Service Plan. This option is ideal for solutions with a limited number of containers that do not require an orchestration platform.”

Please change:  “The easiest way to move to containers on Azure is to deploy containers to App Service for Containers; however, this option does not provide the typical management tools for container orchestration -- that can provide load balancing, dynamic discovery, self-healing, and a holistic approach to container monitoring.” 
--to--
“The easiest way to move to containers on Azure is to deploy containers to App Service for Containers; however, this option does not provide a container orchestration platform."

**Comment by jamesrcounts** [comment]
Thanks again
