### ISSUE TITLE
bit.ly download links don't work.. 

### ISSUE THREAD

**Issue by mwasham** [Microsoft/MCW-Containers-and-DevOps#88]

**Comment by DawnmarieDesJardins** [comment]
@jamesrcounts 
Hi Jim,  A new issue was opened today, please make sure this is addressed in the update you're currently working on.
Thanks, Dawnamrie

**Comment by jamesrcounts** [comment]
@ZoinerTejada @kylebunting @michelebusta Can one of you look at this,  I don't have access to bit.ly

**Comment by mwasham** [comment]
FYI - just realized I was looking at the March update.. (the infrastructure link).

**Comment by DawnmarieDesJardins** [comment]
Closing issue - addressed in March 2019 update
