### ISSUE TITLE
Github integration?

### ISSUE THREAD

**Issue by NoureenS** [microsoft/MCW-Containers-and-DevOps#89]
Will content be updated to add GitHub in this workshop?

**Comment by waltermyersiii** [comment]
Specifically what are you looking for?

**Comment by kevinhillinger** [comment]
Closing this issue, as it's aging and non-specific. @NoureenS, it's great to see the willingness for suggesting improvements. Please provide specifics in the suggestions including:
- which portion of the MCW to improve (HOL or whiteboard)
- is this a content update or a significant material change?
- and finally, how you would suggest the implementation of the update/change

Thanks!

**Comment by NoureenS** [comment]
Thanks Kevin. We spoke offline with Walter on this.

Regards,

Noureen
