### ISSUE TITLE
Setup markdown - AKS

### ISSUE THREAD

**Issue by bspann** [Microsoft/MCW-Containers-and-DevOps#9]
In the setup.md file, Task 10 talks about setting up ALS but the instructions and screen captures are outdated.  New instructions should be added with updated screen captures.

**Comment by jamesrcounts** [comment]
Hi there, I think you may be on the master branch, I just tested the steps on the June-2018-update branch and the screenshots there match what I just saw in the portal.

**Comment by DawnmarieDesJardins** [comment]
Closing. correct on June-2018-update branch.
