### ISSUE TITLE
Use of bower outdated 

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/MCW-Containers-and-DevOps#90]
Bower has been deprecated since pretty much 2017. We should remove this as a dependency in the lab as it gives the impression that we are behind the times.

However, I think this is a low priority issue.

**Comment by waltermyersiii** [comment]
Thanks, Kevin!

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.  Addressed in the recent update.
