### ISSUE TITLE
Error in proctor guide

### ISSUE THREAD

**Issue by shawnweisfeld** [microsoft/MCW-Containers-and-DevOps#94]
This page says "Azure Container Registry itself is a free service." however it has a daily cost, of at least $0.17 per day...

https://github.com/microsoft/MCW-Containers-and-DevOps/blob/master/Whiteboard%20design%20session/WDS%20trainer%20guide%20-%20Containers%20and%20DevOps.md

https://azure.microsoft.com/en-us/pricing/details/container-registry/

**Comment by jamesrcounts** [comment]
@michelebusta can you provide some updated language for the WDS?
