### ISSUE TITLE
yaml builds for azuredevops

### ISSUE THREAD

**Issue by SychevIgor** [microsoft/MCW-Containers-and-DevOps#97]
It's not a bug report, it's feature request.
As I've seen - Microsoft more and more focusing our attention on yaml based CI builds in Azure DevOps, but in this guide we are using Designer Based Build
It would be nice, if in a guide, Microsoft will add yaml files for CI process. It will make this lab closer to Microsoft own best practices and speedup the lab it self. (it's really hard to pass all step during 4h slot)

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved.  Addressed in the recent update.
